package com.example.demo.model.entities;

import com.fasterxml.jackson.annotation.JsonBackReference;
import lombok.Data;
import jakarta.persistence.*;

import java.util.List;

@Entity
@Table(name = "groupe")
@Data // Lombok annotation to generate getters/setters, toString, equals, hashCode, etc.
public class Groupe {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "num_groupe")
    private String numGroupe;

    @ManyToOne
    @JoinColumn(name = "thematique_id")
    @JsonBackReference
    private Thematique thematique;

    @ManyToMany
    private List<Utilisateur> utilisateurs;

    // Constructors, getters, setters, toString, equals, and hashCode will be automatically generated by Lombok
}

