package com.example.demo.model.entities;

import lombok.Data;

import jakarta.persistence.*;

@Entity
@Table(name = "q_reponse")
@Data
public class Q_Reponse {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "reponse_text", nullable = false)
    private String reponse;

    @ManyToOne
    @JoinColumn(name = "question_id", referencedColumnName = "id")
    private Question question;

    @ManyToOne
    @JoinColumn(name = "evaluation_id", referencedColumnName = "id")
    private Evaluation evaluation;

    // Constructors, getters, setters, toString, equals, and hashCode will be automatically generated by Lombok
}

