package com.example.demo.model.entities;

import lombok.Data;

import jakarta.persistence.*;

@Entity
@Table(name = "question")
@Data
public class Question {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "question_text", nullable = false)
    private String questionText;

    // Constructors, getters, setters, toString, equals, and hashCode will be automatically generated by Lombok
}

